DROP DATABASE IF EXISTS creativeWeb_db;
CREATE DATABASE creativeWeb_db;



insert into user (id, name, email, password, github) values (1, 'Bren Derricoat', 'bderricoat0@irs.gov', 'uxAjEPf6', 'http://networksolutions.com/vestibulum/sagittis.jpg?mauris=nunc&eget=rhoncus&massa=dui');
insert into user (id, name, email, password, github) values (2, 'Tedi Sherbrook', 'tsherbrook1@wikimedia.org', 'sFEpMAKgdg', 'http://mail.ru/dictumst/morbi/vestibulum/velit/id/pretium/iaculis.jpg?auctor=nibh&gravida=ligula&sem=nec&praesent=sem&id=duis&massa=aliquam&id=convallis&nisl=nunc&venenatis=proin&lacinia=at&aenean=turpis&sit=a&amet=pede&justo=posuere&morbi=nonummy&ut=integer&odio=non&cras=velit&mi=donec&pede=diam&malesuada=neque&in=vestibulum&imperdiet=eget&et=vulputate&commodo=ut&vulputate=ultrices&justo=vel&in=augue&blandit=vestibulum&ultrices=ante&enim=ipsum&lorem=primis&ipsum=in&dolor=faucibus&sit=orci&amet=luctus&consectetuer=et&adipiscing=ultrices&elit=posuere&proin=cubilia&interdum=curae&mauris=donec&non=pharetra&ligula=magna&pellentesque=vestibulum&ultrices=aliquet&phasellus=ultrices&id=erat&sapien=tortor&in=sollicitudin&sapien=mi&iaculis=sit&congue=amet&vivamus=lobortis&metus=sapien&arcu=sapien&adipiscing=non&molestie=mi&hendrerit=integer&at=ac&vulputate=neque&vitae=duis&nisl=bibendum&aenean=morbi&lectus=non&pellentesque=quam&eget=nec&nunc=dui&donec=luctus&quis=rutrum&orci=nulla&eget=tellus&orci=in&vehicula=sagittis&condimentum=dui&curabitur=vel&in=nisl&libero=duis&ut=ac&massa=nibh');
insert into user (id, name, email, password, github) values (3, 'Jillane Sinnat', 'jsinnat2@sbwire.com', 'mKfQLTG00r', 'https://moonfruit.com/ipsum/praesent/blandit/lacinia/erat/vestibulum/sed.jpg?ac=nunc');
insert into user (id, name, email, password, github) values (4, 'Sterling Sambeck', 'ssambeck3@opensource.org', 'SK5iJW1eWu', 'https://typepad.com/hac/habitasse/platea/dictumst.js?fusce=odio&consequat=elementum&nulla=eu&nisl=interdum&nunc=eu&nisl=tincidunt&duis=in&bibendum=leo&felis=maecenas&sed=pulvinar&interdum=lobortis&venenatis=est&turpis=phasellus&enim=sit&blandit=amet&mi=erat&in=nulla&porttitor=tempus');
insert into user (id, name, email, password, github) values (5, 'Chaim Earey', 'cearey4@storify.com', 'qcQyAFGH16f', 'http://ow.ly/phasellus/id/sapien.xml?dui=morbi&nec=odio&nisi=odio&volutpat=elementum&eleifend=eu');
insert into user (id, name, email, password, github) values (6, 'Jermayne Ascraft', 'jascraft5@artisteer.com', 'hIB2Yhb', 'https://bing.com/quisque.aspx?elementum=donec&eu=ut&interdum=mauris&eu=eget&tincidunt=massa&in=tempor&leo=convallis&maecenas=nulla&pulvinar=neque&lobortis=libero&est=convallis&phasellus=eget&sit=eleifend&amet=luctus&erat=ultricies&nulla=eu&tempus=nibh&vivamus=quisque&in=id&felis=justo&eu=sit&sapien=amet&cursus=sapien&vestibulum=dignissim&proin=vestibulum&eu=vestibulum&mi=ante&nulla=ipsum&ac=primis&enim=in&in=faucibus&tempor=orci&turpis=luctus&nec=et&euismod=ultrices&scelerisque=posuere&quam=cubilia&turpis=curae&adipiscing=nulla&lorem=dapibus&vitae=dolor&mattis=vel&nibh=est&ligula=donec&nec=odio&sem=justo&duis=sollicitudin&aliquam=ut&convallis=suscipit&nunc=a&proin=feugiat&at=et&turpis=eros&a=vestibulum&pede=ac&posuere=est&nonummy=lacinia&integer=nisi&non=venenatis&velit=tristique&donec=fusce&diam=congue&neque=diam&vestibulum=id');
insert into user (id, name, email, password, github) values (7, 'Yurik Rydzynski', 'yrydzynski6@ihg.com', 'qBfMIBJ', 'http://pinterest.com/sapien/cum/sociis/natoque.jsp?erat=ipsum&id=integer&mauris=a&vulputate=nibh&elementum=in&nullam=quis&varius=justo&nulla=maecenas&facilisi=rhoncus&cras=aliquam&non=lacus&velit=morbi&nec=quis&nisi=tortor&vulputate=id&nonummy=nulla&maecenas=ultrices&tincidunt=aliquet&lacus=maecenas&at=leo&velit=odio&vivamus=condimentum&vel=id&nulla=luctus&eget=nec&eros=molestie&elementum=sed&pellentesque=justo&quisque=pellentesque&porta=viverra&volutpat=pede&erat=ac&quisque=diam&erat=cras&eros=pellentesque&viverra=volutpat&eget=dui&congue=maecenas&eget=tristique&semper=est&rutrum=et&nulla=tempus&nunc=semper&purus=est&phasellus=quam&in=pharetra&felis=magna&donec=ac&semper=consequat&sapien=metus&a=sapien&libero=ut&nam=nunc&dui=vestibulum&proin=ante');
insert into user (id, name, email, password, github) values (8, 'Padgett Houtby', 'phoutby7@goo.gl', 'ulwpoVTyI', 'http://wikipedia.org/amet/eleifend/pede.aspx?donec=nulla&quis=mollis&orci=molestie&eget=lorem&orci=quisque&vehicula=ut&condimentum=erat&curabitur=curabitur&in=gravida&libero=nisi&ut=at&massa=nibh&volutpat=in&convallis=hac&morbi=habitasse&odio=platea&odio=dictumst&elementum=aliquam&eu=augue&interdum=quam&eu=sollicitudin&tincidunt=vitae&in=consectetuer&leo=eget&maecenas=rutrum&pulvinar=at&lobortis=lorem&est=integer&phasellus=tincidunt&sit=ante&amet=vel&erat=ipsum&nulla=praesent&tempus=blandit&vivamus=lacinia&in=erat&felis=vestibulum&eu=sed&sapien=magna&cursus=at&vestibulum=nunc&proin=commodo&eu=placerat&mi=praesent&nulla=blandit&ac=nam&enim=nulla');
insert into user (id, name, email, password, github) values (9, 'Joana Crawford', 'jcrawford8@bizjournals.com', 'OKNoBo6xqQa', 'https://rakuten.co.jp/rutrum/rutrum/neque/aenean.aspx?ridiculus=dapibus&mus=nulla&vivamus=suscipit&vestibulum=ligula&sagittis=in&sapien=lacus&cum=curabitur&sociis=at&natoque=ipsum');
insert into user (id, name, email, password, github) values (10, 'Aubrey Burnham', 'aburnham9@blogs.com', 'WXySqjKzj', 'http://tamu.edu/erat.html?id=libero&justo=nullam&sit=sit&amet=amet&sapien=turpis&dignissim=elementum&vestibulum